### ISSUE TITLE
Please make LICENSE

### ISSUE THREAD

**Issue by ykeisuke** [adrianjost/SmartLight-Web-Client#1]
Hello.
This [sourcecode](https://github.com/adrianjost/SmartLight-Firebase/blob/f75db5fe55db3f29192213967295609e31d3c706/src/components/modals/controlModal.vue) was very helpful for me. But, not set the license.
Will you make the license to this repository?

I like MIT LICENSE! ʕ > з < ʔ
Thank you.

**Comment by adrianjost** [comment]
Feel free to use everything you find here as long as it's not for use in a commercial product. At the moment I don't have time to add a proper licence but will do so as soon as possible.

**Comment by ykeisuke** [comment]
@adrianjost Okay. I did understand. Thank you

**Comment by adrianjost** [comment]
Solved with #7
